select * from BEST_PRO_VIEW;
SELECT * FROM NEW_PRO_VIEW;
 
select * from product;
update product set image = 'w22.jpg' where pseq = 33;

SELECT * FROM member;

SELECT * FROM address;

update member set ZIP_NUM = '1234' where id = 'juno';


SELECT * FROM PRODUCT WHERE KIND = '6' ORDER BY PSEQ DESC;


SELECT * FROM ORDER_VIEW WHERE OSEQ = 6 ORDER BY OSEQ DESC;

SELECT * FROM ORDER_VIEW WHERE OSEQ = 8 AND RESULT LIKE '%1%' ORDER BY OSEQ DESC;

SELECT * FROM ORDER_VIEW WHERE OSEQ = 5;

SELECT * FROM ORDER_VIEW WHERE ID = 'juno' AND RESULT LIKE '%'||'%'||'%' AND OSEQ = 16;

SELECT * FROM MEMBER;
UPDATE MEMBER SET PHONE = '010' WHERE ID = 'juno';

SELECT * FROM (
SELECT * FROM (
SELECT ROWNUM AS RN, P.* FROM ((
SELECT * FROM PRODUCT ORDER BY PSEQ DESC) P))
WHERE RN >= 1)
WHERE RN <= 10;


select * from WORKER;

select * from product;